### ISSUE TITLE
Small bug with current in isopotential.ode

### ISSUE THREAD

**Issue by jrieke** [cengique/drosophila-aCC-L3-motoneuron-model#7]
@cengique There's a small bug in the original isopotential.ode file. The line

    global 1 t {I=Ihold}

doesn't have any effect, the current stays at 0 in the beginning. It isn't a major thing because the current goes to Ipulse=0 anyway after 10ms, but should I fix it (by setting ```par I=-12``` [in this line](https://github.com/cengique/drosophila-aCC-L3-motoneuron-model/blob/master/xpp-models/isopotential.ode#L72) and removing the line above)?

**Comment by cengique** [comment]
@jrieke are you sure this doesn't work? I use the `Ihold` parameter regularly to set the initial conditions. Maybe it's best to leave the XPP file alone until I take a look at it. I also wouldn't want a hardcoded number in there.

**Comment by jrieke** [comment]
@cengique That's what I get when I plot ```I``` vs time with the current version of the file. As you can see, it is 0 right from the start (this persists when I do ```nout=1```, so it isn't just a feature of the output/plot).
![image](https://cloud.githubusercontent.com/assets/5103165/9690383/443f90f2-533c-11e5-9eae-b1eb5d9619e4.png)

```Ihold``` is not the problem, I think it's related to the ```global 1 t``` part. I just tested it again, whenever I do ```global 1 t-6``` or anything greater than 6, it works (meaning it sets the current to ```Ihold``` after 6ms (or accordingly for other values)); anything below 6 doesn't work (the line is simply ignored in that case and ```I``` equals 0 from the start).

**Comment by cengique** [comment]
@jrieke Sorry for the late reply, I was out of town for a few days. You may be right; I think the original start time for the pulse may have been later. Although I'm pretty sure that I was using `Ihold` in my experiments.

**Comment by jrieke** [comment]
@cengique I made the current pulse start at 10 ms for now and added a comment in the file (see [here](https://github.com/cengique/drosophila-aCC-L3-motoneuron-model/blob/master/xpp-models/isopotential.ode#L62)) to bring it into alignment with the figures in the paper and the NeuroML2 version. The original model is in the v1.0 release as you suggested. Let me know how you want to handle this eventually.

**Comment by cengique** [comment]
@jrieke Sadly, you're right, this is a bug in XPP. Thanks for finding it! My files show the same behavior. And I can't even find a nice way to initialize the parameter `I` to `Ihold` in XPP. Nevertheless, `I=Ihold` happens at the end of simulation, so that value is kept next time you start, which effectively results in the desired behavior. Meaning that model results are not affected by this bug drastically I hope.

Your additions are fine with me. I tried using the `init` and `aux` commands, but they don't work with parameters. If you're not planning a further use for the XPP model, I'd just leave it this way for now.

**Comment by jrieke** [comment]
Alright, I just updated the comment in the file to describe the new situation.
